-- Rollback-only fixtures in the new Supabase project. No real records or durable users.
BEGIN;
INSERT INTO auth.users(id) VALUES ('00000000-0000-4000-8000-000000000001'), ('00000000-0000-4000-8000-000000000002');
INSERT INTO public."application_events" ("operation_id", "owner_id", "application_id", "action", "snapshot", "previous", "happened_at", "local_date", "request") VALUES ('fixture', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', NULL, 'fixture', 'fixture', 'fixture');
INSERT INTO public."applications" ("id", "owner_id", "institution", "country", "project_title", "supervisor", "link", "deadline", "notes", "next_action", "stage", "checklist", "submission_date", "submission_task_id", "created_at", "updated_at", "version", "opportunity") VALUES ('supabase-test-applications', '00000000-0000-4000-8000-000000000001', 'fixture', '', '', '', '', NULL, '', '', 'Shortlisted', '[]', NULL, NULL, 'fixture', 'fixture', 1, '{}');
INSERT INTO public."day_plans" ("owner_id", "date", "data", "updated_at", "version") VALUES ('00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', 1);
INSERT INTO public."day_templates" ("id", "owner_id", "data", "updated_at", "version") VALUES ('supabase-test-day_templates', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 1);
INSERT INTO public."events" ("operation_id", "owner_id", "task_id", "action", "snapshot", "previous", "happened_at", "local_date", "request") VALUES ('fixture', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', NULL, 'fixture', 'fixture', 'fixture');
INSERT INTO public."focus_sessions" ("id", "owner_id", "duration_ms", "remaining_ms", "end_at", "status", "phone_free", "completion_date", "active_key", "created_at", "updated_at", "version") VALUES ('supabase-test-focus_sessions', '00000000-0000-4000-8000-000000000001', 1, 1, NULL, 'fixture', NULL, NULL, NULL, 'fixture', 'fixture', 1);
INSERT INTO public."habit_events" ("operation_id", "owner_id", "entity_id", "entity_type", "action", "snapshot", "previous", "happened_at", "local_date", "request") VALUES ('fixture', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', 'fixture', NULL, 'fixture', 'fixture', 'fixture');
INSERT INTO public."habit_records" ("id", "owner_id", "kind", "data", "activity_date", "completion_date", "status", "created_at", "updated_at", "version") VALUES ('supabase-test-habit_records', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', NULL, 'fixture', 'fixture', 'fixture', 1);
INSERT INTO public."motivation_settings" ("owner_id", "data", "version", "updated_at") VALUES ('00000000-0000-4000-8000-000000000001', 'fixture', 1, 'fixture');
INSERT INTO public."planning_events" ("operation_id", "owner_id", "entity_id", "entity_type", "snapshot", "previous", "happened_at", "request") VALUES ('fixture', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', NULL, 'fixture', 'fixture');
INSERT INTO public."points_awards" ("id", "owner_id", "activity_key", "kind", "amount", "active", "activity_date", "label", "first_awarded_at") VALUES ('supabase-test-points_awards', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 1, 0, 'fixture', 'fixture', 'fixture');
INSERT INTO public."points_ledger" ("event_key", "owner_id", "activity_key", "action", "delta", "activity_date", "previous_date", "label", "happened_at", "local_date") VALUES ('fixture', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 1, NULL, NULL, 'fixture', 'fixture', 'fixture');
INSERT INTO public."redemptions" ("id", "owner_id", "reward_id", "name", "cost", "refunded", "created_at", "local_date", "version") VALUES ('supabase-test-redemptions', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 1, 0, 'fixture', 'fixture', 1);
INSERT INTO public."rewards" ("id", "owner_id", "name", "description", "cost", "archived", "created_at", "updated_at", "version") VALUES ('supabase-test-rewards', '00000000-0000-4000-8000-000000000001', 'fixture', '', 1, 0, 'fixture', 'fixture', 1);
INSERT INTO public."tasks" ("id", "owner_id", "title", "goal", "kind", "due_date", "minutes", "completed_at", "completed_date", "created_at", "updated_at", "version", "application_id", "application_action_key", "workspace_record_id", "habit_record_id", "custom_points") VALUES ('supabase-test-tasks', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', 'fixture', 1, NULL, NULL, 'fixture', 'fixture', 1, NULL, NULL, NULL, NULL, 0);
INSERT INTO public."weekly_reviews" ("owner_id", "week_start", "data", "updated_at", "version") VALUES ('00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', 1);
INSERT INTO public."workspace_catalog" ("id", "owner_id", "kind", "name", "parent_id", "created_at", "updated_at", "version") VALUES ('supabase-test-workspace_catalog', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', NULL, 'fixture', 'fixture', 1);
INSERT INTO public."workspace_events" ("operation_id", "owner_id", "entity_id", "entity_type", "action", "snapshot", "previous", "happened_at", "local_date", "request") VALUES ('fixture', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', 'fixture', 'fixture', NULL, 'fixture', 'fixture', 'fixture');
INSERT INTO public."workspace_records" ("id", "owner_id", "kind", "data", "source_record_id", "followup_key", "created_at", "updated_at", "version") VALUES ('supabase-test-workspace_records', '00000000-0000-4000-8000-000000000001', 'fixture', 'fixture', NULL, NULL, 'fixture', 'fixture', 1);
INSERT INTO public."workspace_settings" ("owner_id", "data", "version", "updated_at") VALUES ('00000000-0000-4000-8000-000000000001', 'fixture', 1, 'fixture');
CREATE TEMP TABLE checks(label text, passed boolean);
GRANT INSERT ON checks TO authenticated, anon;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',true);
INSERT INTO checks SELECT 'owner read application_events', count(*)=1 FROM public."application_events";
INSERT INTO checks SELECT 'owner read applications', count(*)=1 FROM public."applications";
INSERT INTO checks SELECT 'owner read day_plans', count(*)=1 FROM public."day_plans";
INSERT INTO checks SELECT 'owner read day_templates', count(*)=1 FROM public."day_templates";
INSERT INTO checks SELECT 'owner read events', count(*)=1 FROM public."events";
INSERT INTO checks SELECT 'owner read focus_sessions', count(*)=1 FROM public."focus_sessions";
INSERT INTO checks SELECT 'owner read habit_events', count(*)=1 FROM public."habit_events";
INSERT INTO checks SELECT 'owner read habit_records', count(*)=1 FROM public."habit_records";
INSERT INTO checks SELECT 'owner read motivation_settings', count(*)=1 FROM public."motivation_settings";
INSERT INTO checks SELECT 'owner read planning_events', count(*)=1 FROM public."planning_events";
INSERT INTO checks SELECT 'owner read points_awards', count(*)=1 FROM public."points_awards";
INSERT INTO checks SELECT 'owner read points_ledger', count(*)=1 FROM public."points_ledger";
INSERT INTO checks SELECT 'owner read redemptions', count(*)=1 FROM public."redemptions";
INSERT INTO checks SELECT 'owner read rewards', count(*)=1 FROM public."rewards";
INSERT INTO checks SELECT 'owner read tasks', count(*)=1 FROM public."tasks";
INSERT INTO checks SELECT 'owner read weekly_reviews', count(*)=1 FROM public."weekly_reviews";
INSERT INTO checks SELECT 'owner read workspace_catalog', count(*)=1 FROM public."workspace_catalog";
INSERT INTO checks SELECT 'owner read workspace_events', count(*)=1 FROM public."workspace_events";
INSERT INTO checks SELECT 'owner read workspace_records', count(*)=1 FROM public."workspace_records";
INSERT INTO checks SELECT 'owner read workspace_settings', count(*)=1 FROM public."workspace_settings";
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',true);
INSERT INTO checks SELECT 'cross-account isolation application_events', count(*)=0 FROM public."application_events";
INSERT INTO checks SELECT 'cross-account isolation applications', count(*)=0 FROM public."applications";
INSERT INTO checks SELECT 'cross-account isolation day_plans', count(*)=0 FROM public."day_plans";
INSERT INTO checks SELECT 'cross-account isolation day_templates', count(*)=0 FROM public."day_templates";
INSERT INTO checks SELECT 'cross-account isolation events', count(*)=0 FROM public."events";
INSERT INTO checks SELECT 'cross-account isolation focus_sessions', count(*)=0 FROM public."focus_sessions";
INSERT INTO checks SELECT 'cross-account isolation habit_events', count(*)=0 FROM public."habit_events";
INSERT INTO checks SELECT 'cross-account isolation habit_records', count(*)=0 FROM public."habit_records";
INSERT INTO checks SELECT 'cross-account isolation motivation_settings', count(*)=0 FROM public."motivation_settings";
INSERT INTO checks SELECT 'cross-account isolation planning_events', count(*)=0 FROM public."planning_events";
INSERT INTO checks SELECT 'cross-account isolation points_awards', count(*)=0 FROM public."points_awards";
INSERT INTO checks SELECT 'cross-account isolation points_ledger', count(*)=0 FROM public."points_ledger";
INSERT INTO checks SELECT 'cross-account isolation redemptions', count(*)=0 FROM public."redemptions";
INSERT INTO checks SELECT 'cross-account isolation rewards', count(*)=0 FROM public."rewards";
INSERT INTO checks SELECT 'cross-account isolation tasks', count(*)=0 FROM public."tasks";
INSERT INTO checks SELECT 'cross-account isolation weekly_reviews', count(*)=0 FROM public."weekly_reviews";
INSERT INTO checks SELECT 'cross-account isolation workspace_catalog', count(*)=0 FROM public."workspace_catalog";
INSERT INTO checks SELECT 'cross-account isolation workspace_events', count(*)=0 FROM public."workspace_events";
INSERT INTO checks SELECT 'cross-account isolation workspace_records', count(*)=0 FROM public."workspace_records";
INSERT INTO checks SELECT 'cross-account isolation workspace_settings', count(*)=0 FROM public."workspace_settings";
SELECT set_config('request.jwt.claim.sub','',true);
INSERT INTO checks SELECT 'missing identity application_events', count(*)=0 FROM public."application_events";
INSERT INTO checks SELECT 'missing identity applications', count(*)=0 FROM public."applications";
INSERT INTO checks SELECT 'missing identity day_plans', count(*)=0 FROM public."day_plans";
INSERT INTO checks SELECT 'missing identity day_templates', count(*)=0 FROM public."day_templates";
INSERT INTO checks SELECT 'missing identity events', count(*)=0 FROM public."events";
INSERT INTO checks SELECT 'missing identity focus_sessions', count(*)=0 FROM public."focus_sessions";
INSERT INTO checks SELECT 'missing identity habit_events', count(*)=0 FROM public."habit_events";
INSERT INTO checks SELECT 'missing identity habit_records', count(*)=0 FROM public."habit_records";
INSERT INTO checks SELECT 'missing identity motivation_settings', count(*)=0 FROM public."motivation_settings";
INSERT INTO checks SELECT 'missing identity planning_events', count(*)=0 FROM public."planning_events";
INSERT INTO checks SELECT 'missing identity points_awards', count(*)=0 FROM public."points_awards";
INSERT INTO checks SELECT 'missing identity points_ledger', count(*)=0 FROM public."points_ledger";
INSERT INTO checks SELECT 'missing identity redemptions', count(*)=0 FROM public."redemptions";
INSERT INTO checks SELECT 'missing identity rewards', count(*)=0 FROM public."rewards";
INSERT INTO checks SELECT 'missing identity tasks', count(*)=0 FROM public."tasks";
INSERT INTO checks SELECT 'missing identity weekly_reviews', count(*)=0 FROM public."weekly_reviews";
INSERT INTO checks SELECT 'missing identity workspace_catalog', count(*)=0 FROM public."workspace_catalog";
INSERT INTO checks SELECT 'missing identity workspace_events', count(*)=0 FROM public."workspace_events";
INSERT INTO checks SELECT 'missing identity workspace_records', count(*)=0 FROM public."workspace_records";
INSERT INTO checks SELECT 'missing identity workspace_settings', count(*)=0 FROM public."workspace_settings";
RESET ROLE;
INSERT INTO checks VALUES ('anonymous blocked application_events', NOT has_table_privilege('anon','public.application_events','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked application_events', NOT has_table_privilege('authenticated','public.application_events','INSERT') AND NOT has_table_privilege('authenticated','public.application_events','UPDATE') AND NOT has_table_privilege('authenticated','public.application_events','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked applications', NOT has_table_privilege('anon','public.applications','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked applications', NOT has_table_privilege('authenticated','public.applications','INSERT') AND NOT has_table_privilege('authenticated','public.applications','UPDATE') AND NOT has_table_privilege('authenticated','public.applications','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked day_plans', NOT has_table_privilege('anon','public.day_plans','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked day_plans', NOT has_table_privilege('authenticated','public.day_plans','INSERT') AND NOT has_table_privilege('authenticated','public.day_plans','UPDATE') AND NOT has_table_privilege('authenticated','public.day_plans','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked day_templates', NOT has_table_privilege('anon','public.day_templates','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked day_templates', NOT has_table_privilege('authenticated','public.day_templates','INSERT') AND NOT has_table_privilege('authenticated','public.day_templates','UPDATE') AND NOT has_table_privilege('authenticated','public.day_templates','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked events', NOT has_table_privilege('anon','public.events','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked events', NOT has_table_privilege('authenticated','public.events','INSERT') AND NOT has_table_privilege('authenticated','public.events','UPDATE') AND NOT has_table_privilege('authenticated','public.events','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked focus_sessions', NOT has_table_privilege('anon','public.focus_sessions','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked focus_sessions', NOT has_table_privilege('authenticated','public.focus_sessions','INSERT') AND NOT has_table_privilege('authenticated','public.focus_sessions','UPDATE') AND NOT has_table_privilege('authenticated','public.focus_sessions','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked habit_events', NOT has_table_privilege('anon','public.habit_events','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked habit_events', NOT has_table_privilege('authenticated','public.habit_events','INSERT') AND NOT has_table_privilege('authenticated','public.habit_events','UPDATE') AND NOT has_table_privilege('authenticated','public.habit_events','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked habit_records', NOT has_table_privilege('anon','public.habit_records','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked habit_records', NOT has_table_privilege('authenticated','public.habit_records','INSERT') AND NOT has_table_privilege('authenticated','public.habit_records','UPDATE') AND NOT has_table_privilege('authenticated','public.habit_records','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked motivation_settings', NOT has_table_privilege('anon','public.motivation_settings','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked motivation_settings', NOT has_table_privilege('authenticated','public.motivation_settings','INSERT') AND NOT has_table_privilege('authenticated','public.motivation_settings','UPDATE') AND NOT has_table_privilege('authenticated','public.motivation_settings','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked planning_events', NOT has_table_privilege('anon','public.planning_events','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked planning_events', NOT has_table_privilege('authenticated','public.planning_events','INSERT') AND NOT has_table_privilege('authenticated','public.planning_events','UPDATE') AND NOT has_table_privilege('authenticated','public.planning_events','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked points_awards', NOT has_table_privilege('anon','public.points_awards','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked points_awards', NOT has_table_privilege('authenticated','public.points_awards','INSERT') AND NOT has_table_privilege('authenticated','public.points_awards','UPDATE') AND NOT has_table_privilege('authenticated','public.points_awards','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked points_ledger', NOT has_table_privilege('anon','public.points_ledger','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked points_ledger', NOT has_table_privilege('authenticated','public.points_ledger','INSERT') AND NOT has_table_privilege('authenticated','public.points_ledger','UPDATE') AND NOT has_table_privilege('authenticated','public.points_ledger','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked redemptions', NOT has_table_privilege('anon','public.redemptions','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked redemptions', NOT has_table_privilege('authenticated','public.redemptions','INSERT') AND NOT has_table_privilege('authenticated','public.redemptions','UPDATE') AND NOT has_table_privilege('authenticated','public.redemptions','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked rewards', NOT has_table_privilege('anon','public.rewards','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked rewards', NOT has_table_privilege('authenticated','public.rewards','INSERT') AND NOT has_table_privilege('authenticated','public.rewards','UPDATE') AND NOT has_table_privilege('authenticated','public.rewards','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked tasks', NOT has_table_privilege('anon','public.tasks','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked tasks', NOT has_table_privilege('authenticated','public.tasks','INSERT') AND NOT has_table_privilege('authenticated','public.tasks','UPDATE') AND NOT has_table_privilege('authenticated','public.tasks','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked weekly_reviews', NOT has_table_privilege('anon','public.weekly_reviews','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked weekly_reviews', NOT has_table_privilege('authenticated','public.weekly_reviews','INSERT') AND NOT has_table_privilege('authenticated','public.weekly_reviews','UPDATE') AND NOT has_table_privilege('authenticated','public.weekly_reviews','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked workspace_catalog', NOT has_table_privilege('anon','public.workspace_catalog','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked workspace_catalog', NOT has_table_privilege('authenticated','public.workspace_catalog','INSERT') AND NOT has_table_privilege('authenticated','public.workspace_catalog','UPDATE') AND NOT has_table_privilege('authenticated','public.workspace_catalog','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked workspace_events', NOT has_table_privilege('anon','public.workspace_events','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked workspace_events', NOT has_table_privilege('authenticated','public.workspace_events','INSERT') AND NOT has_table_privilege('authenticated','public.workspace_events','UPDATE') AND NOT has_table_privilege('authenticated','public.workspace_events','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked workspace_records', NOT has_table_privilege('anon','public.workspace_records','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked workspace_records', NOT has_table_privilege('authenticated','public.workspace_records','INSERT') AND NOT has_table_privilege('authenticated','public.workspace_records','UPDATE') AND NOT has_table_privilege('authenticated','public.workspace_records','DELETE'));
INSERT INTO checks VALUES ('anonymous blocked workspace_settings', NOT has_table_privilege('anon','public.workspace_settings','SELECT'));
INSERT INTO checks VALUES ('browser writes blocked workspace_settings', NOT has_table_privilege('authenticated','public.workspace_settings','INSERT') AND NOT has_table_privilege('authenticated','public.workspace_settings','UPDATE') AND NOT has_table_privilege('authenticated','public.workspace_settings','DELETE'));
INSERT INTO checks VALUES ('identity map private', NOT has_schema_privilege('authenticated','steady_private','USAGE') AND NOT has_schema_privilege('anon','steady_private','USAGE'));
SELECT count(*) AS checks, count(*) FILTER (WHERE NOT passed) AS failures FROM checks;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM checks WHERE NOT passed) THEN RAISE EXCEPTION 'Steady isolation checks failed'; END IF; END $$;
ROLLBACK;
