'use client';
import {CalendarDays,ExternalLink} from 'lucide-react';
import {compareApplications,deadlineBadge,deadlineDays,displayDeadline,needsPreparation,type Application,type ApplicationSort} from '@/lib/applications';
import {prettyDate} from '@/lib/tasks';
import {useState} from 'react';
export function Deadline({application:a,today,detailed=false}:{application:Application;today:string;detailed?:boolean}){
 const date=displayDeadline(a);if(!date)return <span className="deadline-caption">No deadline set</span>;
 const days=deadlineDays(date,today),badge=deadlineBadge(a,today),closing=a.opportunity?.closingAt;
 return <div className="deadline-block"><span className={'application-deadline '+(needsPreparation(a)&&days<=7?'urgent':'')}><CalendarDays size={14}/>{prettyDate(date)} {date.slice(0,4)}{<strong>{badge==='Deadline passed'?(days<0?`${Math.abs(days)} days past`:'Closed'):days===0?'Due today':`${days} days remaining`}</strong>}</span>{badge&&<span className={'deadline-badge '+(badge==='Deadline passed'?'passed':days<=7?'within-seven':'')}>{badge}</span>}{detailed&&(closing?<small className="deadline-time">Closes {new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(closing))} IST · Official: {a.opportunity?.closingLabel}</small>:<small className="deadline-time">Date only · closing time not specified</small>)}</div>;
}
export default function UpcomingApplications({applications,today,onOpen}:{applications:Application[];today:string;onOpen:(id:string)=>void}){
 const [sort,setSort]=useState<ApplicationSort>('deadline');
 const active=applications.filter(needsPreparation),earliest=[...active].sort((a,b)=>compareApplications(a,b))[0];
 const positions=active.flatMap(a=>a.opportunity?.preferences?.length?a.opportunity.preferences.map(p=>({application:a,title:`${p.code} — ${p.title}`,rank:p.fitPriority,link:p.link,preference:p.code})): [{application:a,title:a.projectTitle,rank:a.opportunity?.fitPriority,link:a.link,preference:''}]);
 positions.sort((a,b)=>compareApplications({...a.application,opportunity:{...a.application.opportunity,fitPriority:a.rank}},{...b.application,opportunity:{...b.application.opportunity,fitPriority:b.rank}},sort));
 return <section className="upcoming-applications" aria-label="Upcoming PhD opportunities"><div className="section-heading"><div><h2>PhD opportunities</h2><span>{positions.length} pending positions · {active.length} applications</span></div><label>Sort <select aria-label="Sort upcoming applications" value={sort} onChange={e=>setSort(e.target.value as ApplicationSort)}><option value="deadline">Deadline first</option><option value="fit">Fit priority</option></select></label></div>{positions.length?positions.map(p=><article className="upcoming-opportunity" key={p.application.id+p.preference}><div className="opportunity-top"><span className="fit-rank">{p.rank?'Fit priority '+p.rank:'Unranked'}</span><span className={'stage-badge stage-'+p.application.stage.toLowerCase()}>{p.application.stage}</span></div>{p.application.id===earliest?.id&&<strong className="work-next">Work on next — earliest deadline</strong>}<button className="opportunity-title" onClick={()=>onOpen(p.application.id)}>{p.title||p.application.institution}</button><p>{p.application.institution} · {p.application.country||'Country not set'}</p><Deadline application={p.application} today={today}/>{p.preference&&<span className="shared-workflow">One shared UFAST application · PM4 + PM5</span>}{p.application.opportunity?.rolling&&<span className="rolling-note">Rolling review — apply early</span>}<div className="opportunity-links"><button className="text-button" onClick={()=>onOpen(p.application.id)}>Open application</button>{p.link&&<a href={p.link} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>Official advert</a>}</div></article>):<p className="empty-detail">No active PhD opportunities. Submitted and closed applications are saved in History.</p>}</section>;
}
