'use client';
import {useRef,useState} from 'react';
import {ArrowUp,ArrowDown,Star,X,Check,Plus} from 'lucide-react';
import {emptyPlan,pendingTasks,planTotals,planTasks,activityKey,addDays,type DayPlan} from '@/lib/planning';
import {goalNames,duration,prettyDate,type State,type Task} from '@/lib/tasks';
type Props={data:State;busy:boolean;mutate:(p:unknown,message:string,inside?:boolean,endpoint?:string)=>Promise<boolean>;onOpen:(t:Task)=>void;onComplete:(t:Task)=>void};
export default function DayPlanner({data,busy,mutate,onOpen,onComplete}:Props){
 const [selectedDay,setDay]=useState<string|null>(null),[dirty,setDirty]=useState(false),[edited,setDraft]=useState<DayPlan>(()=>data.dayPlans.find(p=>p.date===data.today)||emptyPlan(data.today)),[addId,setAddId]=useState(''),[templateId,setTemplateId]=useState('');
 const [template,setTemplate]=useState<{id:string;operationId:string;name:string;version:number}|null>(null),[selectedWrap,setWrapDate]=useState<string|null>(null),[chosenDestination,setDestination]=useState<string|null>(null);
 const operation=useRef<string|null>(null),day=dirty?edited.date:selectedDay||data.today,wrapDate=selectedWrap||data.today,destination=chosenDestination||addDays(data.today,1);
 const saved=data.dayPlans.find(p=>p.date===day),draft=dirty?edited:saved||emptyPlan(day),totals=planTotals(draft,data),pending=pendingTasks(data),shownPriorityIds=draft.priorityIds.filter(id=>totals.tasks.some(t=>t.id===id)),keys=new Set(draft.taskIds.filter(id=>!draft.decisions[id]).map(id=>data.tasks.find(t=>t.id===id)).filter((t):t is Task=>!!t).map(activityKey));
 const available=pending.filter(t=>!keys.has(activityKey(t))),wrap=data.dayPlans.find(p=>p.date===wrapDate),unfinished=wrap?planTasks(wrap,data).filter(t=>!t.completedAt):[];
 function update(next:DayPlan){setDraft(next);setDirty(true);operation.current=null;}
 async function save(){operation.current??=crypto.randomUUID();const fields={availableMinutes:draft.availableMinutes,taskIds:draft.taskIds,priorityIds:draft.priorityIds,decisions:draft.decisions};if(await mutate({action:'plan',date:day,version:draft.version,operationId:operation.current,fields},'Day plan saved.',false,'/api/planning')){setDirty(false);operation.current=null;}}
 function remove(id:string){update({...draft,taskIds:draft.taskIds.filter(x=>x!==id),priorityIds:draft.priorityIds.filter(x=>x!==id),decisions:Object.fromEntries(Object.entries(draft.decisions).filter(([key])=>key!==id))});}
 function move(id:string,direction:number){const visible=totals.tasks.map(t=>t.id),position=visible.indexOf(id),next=position+direction;if(next<0||next>=visible.length)return;const index=draft.taskIds.indexOf(id),other=draft.taskIds.indexOf(visible[next]),ids=[...draft.taskIds];[ids[index],ids[other]]=[ids[other],ids[index]];update({...draft,taskIds:ids});}
 async function apply(){const t=data.dayTemplates.find(t=>t.id===templateId);if(t&&await mutate({action:'apply',date:day,version:saved?.version||0,templateId:t.id,templateVersion:t.version,operationId:crypto.randomUUID()},'Template applied. Global targets are unchanged.',false,'/api/planning'))setDirty(false);}
 async function saveTemplate(){if(!template)return;const ok=await mutate({action:'template',id:template.id,version:template.version,operationId:template.operationId,fields:{name:template.name,availableMinutes:draft.availableMinutes,taskIds:draft.taskIds,priorityIds:draft.priorityIds}},'Day template saved.',false,'/api/planning');if(ok){if(template.version>0){setDirty(false);setDraft(saved||emptyPlan(day));}setTemplate(null);}}
 async function resolve(taskId:string,decision:'pending'|'rescheduled'){if(!wrap)return;await mutate({action:'resolve',date:wrapDate,version:wrap.version,taskId,decision,operationId:crypto.randomUUID(),...(decision==='rescheduled'?{targetDate:destination,targetVersion:data.dayPlans.find(p=>p.date===destination)?.version||0}:{})},decision==='pending'?'Left pending. Choose a workday when you are ready.':'Work moved to the chosen day. Deadlines are unchanged.',false,'/api/planning');}
 return <section className="daily-planner" aria-label="Daily planning"><div className="section-heading"><div><h2>Plan my day</h2><span>Choose what fits; the rest can wait.</span></div><label className="planner-date">Work date<input aria-label="Plan work date" type="date" min="2000-01-01" max="2100-12-31" value={day} disabled={busy||dirty} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label></div>
 <div className="planner-budget"><label>Available work time (minutes)<input type="number" min={0} max={1440} inputMode="numeric" placeholder="Not set" value={draft.availableMinutes??''} disabled={busy} onChange={e=>update({...draft,availableMinutes:e.target.value===''?null:Number(e.target.value)})}/></label><div className={draft.availableMinutes!==null&&totals.minutes>draft.availableMinutes?'planner-total over-budget':'planner-total'}><strong>{duration(totals.minutes)}</strong><span>planned {draft.availableMinutes!==null?'of '+duration(draft.availableMinutes)+' available':'· available time not set'}</span>{draft.availableMinutes!==null&&totals.minutes>draft.availableMinutes&&<small>{duration(totals.minutes-draft.availableMinutes)} over available time</small>}{totals.missing>0&&<small className="overdue">{totals.missing} missing duration estimate{totals.missing>1?'s':''}; total is incomplete.</small>}</div></div>
 <div className="plan-list">{totals.tasks.map((t,i)=><div className={'plan-row '+(t.completedAt?'completed':'')} key={t.id}><button className="task-check" disabled={busy||dirty} aria-label={(t.completedAt?'Undo completion: ':'Complete: ')+t.title} aria-pressed={!!t.completedAt} onClick={()=>onComplete(t)}>{t.completedAt&&<Check size={15}/>}</button><div className="plan-task-copy"><button className="task-title" disabled={busy} onClick={()=>onOpen(t)}>{t.title}</button><span>{goalNames[t.goal]} · {t.minutes>0?duration(t.minutes):'Missing duration estimate'}{t.dueDate!==day?' · Task due '+prettyDate(t.dueDate):''}</span>{draft.priorityIds.includes(t.id)&&<strong>Main priority {draft.priorityIds.indexOf(t.id)+1}</strong>}</div><div className="plan-row-controls"><button className={draft.priorityIds.includes(t.id)?'plan-priority selected':'plan-priority'} aria-label={(draft.priorityIds.includes(t.id)?'Remove priority: ':'Make a priority: ')+t.title} aria-pressed={draft.priorityIds.includes(t.id)} disabled={busy||(!draft.priorityIds.includes(t.id)&&shownPriorityIds.length>=3)} onClick={()=>update({...draft,priorityIds:draft.priorityIds.includes(t.id)?draft.priorityIds.filter(id=>id!==t.id):[...shownPriorityIds,t.id]})}><Star size={17}/></button><button aria-label={'Move up: '+t.title} disabled={busy||i===0} onClick={()=>move(t.id,-1)}><ArrowUp size={17}/></button><button aria-label={'Move down: '+t.title} disabled={busy||i===totals.tasks.length-1} onClick={()=>move(t.id,1)}><ArrowDown size={17}/></button><button aria-label={'Remove from plan: '+t.title} disabled={busy} onClick={()=>remove(t.id)}><X size={17}/></button></div></div>)}{!totals.tasks.length&&<p className="empty-detail">No work selected for this day. Add pending tasks below.</p>}</div>
 <div className="planner-add"><select aria-label="Choose a pending task for the plan" disabled={busy} value={addId} onChange={e=>setAddId(e.target.value)}><option value="">Choose an existing pending task</option>{(['phd','net','research'] as const).map(goal=><optgroup label={goalNames[goal]} key={goal}>{available.filter(t=>t.goal===goal).map(t=><option key={t.id} value={t.id}>{t.title} · {t.minutes>0?duration(t.minutes):'missing estimate'}</option>)}</optgroup>)}</select><button className="secondary-button" disabled={busy||!available.some(t=>t.id===addId)} onClick={()=>{const chosen=data.tasks.find(t=>t.id===addId);if(!chosen)return;const prior=draft.taskIds.find(id=>{const t=data.tasks.find(t=>t.id===id);return t&&activityKey(t)===activityKey(chosen);}),id=prior||addId;update({...draft,taskIds:prior?draft.taskIds:[...draft.taskIds,id],decisions:Object.fromEntries(Object.entries(draft.decisions).filter(([key])=>key!==id))});setAddId('');}}><Plus size={16}/>Add to plan</button></div>{!pending.length&&<p className="field-help">Create tasks on Applications, Study or Research, then choose them here.</p>}
 <div className="planner-actions"><span className="field-help">{dirty?<strong>Unsaved plan edits. </strong>:saved?<strong>Plan saved. </strong>:null}Up to three main priorities. Work dates do not change application deadlines. Focus time overlaps your work, so it is not added to this total.</span><div><button className="text-button" disabled={busy||!dirty} onClick={()=>{setDirty(false);setDraft(saved||emptyPlan(day));operation.current=null;}}>Discard edits</button><button className="primary-button" disabled={busy||!dirty||!!template?.version} onClick={()=>void save()}>{busy?'Saving…':'Save plan'}</button></div></div>
 <details className="planner-templates"><summary>Day templates</summary><p className="field-help">Save your chosen time, tasks and priorities. Reuse them without creating tasks or changing global targets.</p><div className="planner-add"><select aria-label="Day template" value={templateId} disabled={busy} onChange={e=>setTemplateId(e.target.value)}><option value="">Choose a saved template</option>{data.dayTemplates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><button className="secondary-button" disabled={busy||dirty||!templateId} onClick={()=>void apply()}>Apply template</button><button className="text-button" disabled={busy||dirty||!templateId} onClick={()=>{const t=data.dayTemplates.find(t=>t.id===templateId);if(t){setDraft({...emptyPlan(day),...(saved||{}),availableMinutes:t.availableMinutes,taskIds:t.taskIds,priorityIds:t.priorityIds});setDirty(true);setTemplate({id:t.id,operationId:crypto.randomUUID(),name:t.name,version:t.version});}}}>Edit template</button></div><button className="text-button" disabled={busy} onClick={()=>setTemplate({id:crypto.randomUUID(),operationId:crypto.randomUUID(),name:'Normal day',version:0})}>Save these choices as a template</button>{template&&<div className="template-editor"><label>Template name<input maxLength={80} value={template.name} disabled={busy} placeholder="Normal day, Lab-heavy day or Light day" onChange={e=>setTemplate({...template,name:e.target.value,operationId:crypto.randomUUID()})}/></label><p className="field-help">Uses the time, tasks and priorities shown above. Edit those choices before saving.</p><button className="secondary-button" disabled={busy||!template.name.trim()} onClick={()=>void saveTemplate()}>Save template</button><button className="text-button" disabled={busy} onClick={()=>{if(template.version>0){setDirty(false);setDraft(saved||emptyPlan(day));}setTemplate(null);}}>Cancel</button></div>}</details>
 <details className="unfinished-plans"><summary>Wrap up unfinished work</summary><p className="field-help">Choose what to move. Nothing rolls into tomorrow’s plan automatically.</p><div className="form-columns"><label>Planned day<select value={wrapDate} disabled={busy} onChange={e=>setWrapDate(e.target.value)}><option value={data.today}>{prettyDate(data.today)} · today</option>{data.dayPlans.filter(p=>p.date<data.today).map(p=><option key={p.date} value={p.date}>{prettyDate(p.date)} {p.date.slice(0,4)}</option>)}</select></label><label>Move selected work to<input type="date" min={addDays(wrapDate,1)>data.today?addDays(wrapDate,1):data.today} max="2100-12-31" value={destination} disabled={busy} onChange={e=>setDestination(e.target.value)}/></label></div>{unfinished.length?unfinished.map(t=><div className="unfinished-row" key={t.id}><span>{t.title}</span><div><button className="secondary-button" disabled={busy||dirty||!destination} onClick={()=>void resolve(t.id,'rescheduled')}>Reschedule</button><button className="text-button" disabled={busy||dirty} onClick={()=>void resolve(t.id,'pending')}>Leave pending</button></div></div>):<p className="empty-detail">No unfinished work to decide on for this plan.</p>}{dirty&&<p className="field-help">Save or discard your plan edits before applying a template, completing work or wrapping up.</p>}</details>
 </section>;
}
