'use client';
import {useState,type FormEvent,type ReactNode} from 'react';
import {Dialog} from './unsaved-changes';
import {X} from 'lucide-react';
import {pointKinds,pointLabels,type MotivationSettings} from '@/lib/motivation';
import type {State} from '@/lib/tasks';
export type Mutate=(payload:unknown,message:string,insideForm?:boolean,endpoint?:string)=>Promise<boolean>;
export type MotivationProps={data:State;busy:boolean;mutate:Mutate;formError:string;clearFormError:()=>void;createRequested:number};
export function Modal({open,onClose,busy,title,description,children}:{open:boolean;onClose:()=>void;busy:boolean;title:string;description:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="task-dialog work-dialog" onInteractOutside={e=>{if(busy)e.preventDefault();}} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}}><div className="dialog-heading"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description></div><Dialog.Close className="icon-button" disabled={busy} aria-label="Close form"><X size={20}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function FormActions({busy,onClose,label='Save',disabledSubmit=false}:{busy:boolean;onClose:()=>void;label?:string;disabledSubmit?:boolean}){return <div className="dialog-actions"><button type="button" className="secondary-button" disabled={busy} onClick={onClose} data-draft-dismiss>Cancel</button><button className="primary-button" disabled={busy||disabledSubmit}>{busy?'Saving…':label}</button></div>;}
export function MotivationSettingsForm({data,busy,mutate,formError,onClose,section}:{data:State;busy:boolean;mutate:Mutate;formError:string;onClose:()=>void;section:'points'|'habits'}){
 const [settings,setSettings]=useState<MotivationSettings>(()=>({...data.motivation,points:{...data.motivation.points}})),[operationId]=useState(()=>crypto.randomUUID()),[id]=useState(()=>crypto.randomUUID());
 async function save(e:FormEvent){e.preventDefault();if(await mutate({action:'settings',id,operationId,version:settings.version,fields:settings},'Your settings are saved.',true,'/api/motivation'))onClose();}
 return <form onSubmit={save}><fieldset disabled={busy}>{section==='points'?<>{pointKinds.map(kind=><div key={kind}><label htmlFor={'points-'+kind}>{pointLabels[kind]}</label><input id={'points-'+kind} type="number" inputMode="numeric" min={0} max={100000} required value={settings.points[kind]} onChange={e=>setSettings({...settings,points:{...settings.points,[kind]:Number(e.target.value)}})}/></div>)}<p className="field-help">These values apply to future first awards. Earlier amounts stay saved, including after undo and completion again. Earlier completed work is preserved without automatic points.</p></>:<><label htmlFor="phone-target">Daily distracting-use target (minutes, optional)</label><input id="phone-target" type="number" inputMode="numeric" min={0} max={1440} value={settings.phoneDailyTarget??''} onChange={e=>setSettings({...settings,phoneDailyTarget:e.target.value===''?null:Number(e.target.value)})}/><p className="field-help">Leave blank if you do not want a target. Exceeding it never deducts points.</p><label htmlFor="focus-default">Default focus duration (minutes)</label><input id="focus-default" type="number" inputMode="numeric" min={1} max={240} required value={settings.focusMinutes} onChange={e=>setSettings({...settings,focusMinutes:Number(e.target.value)})}/><label htmlFor="focus-limit">Rewarded focus sessions per India day</label><input id="focus-limit" type="number" inputMode="numeric" min={0} max={50} required value={settings.focusDailyLimit} onChange={e=>setSettings({...settings,focusDailyLimit:Number(e.target.value)})}/><label htmlFor="workout-target">Workout target (minutes)</label><input id="workout-target" type="number" inputMode="numeric" min={1} max={1440} required value={settings.workoutMinutes} onChange={e=>setSettings({...settings,workoutMinutes:Number(e.target.value)})}/><p className="field-help">Rest days are welcome. A completed workout earns one daily award, regardless of the number of entries.</p></>}</fieldset>{formError&&<div className="form-error" role="alert">{formError}</div>}<FormActions busy={busy} onClose={onClose}/></form>;
}
