'use client';
import {useRef,useState} from 'react';
import {useDraftProtection,useUnsavedChanges} from './unsaved-changes';
import {weeklySummary} from '@/lib/weekly-review';
import {weekStart,addDays,pendingTasks,type WeeklyReview} from '@/lib/planning';
import {prettyDate,duration,goalNames,type State} from '@/lib/tasks';
const empty=(start:string):WeeklyReview=>({weekStart:start,wentWell:'',obstacles:'',change:'',priorityIds:[],version:0,updatedAt:''});
export default function ReviewView({data,busy,mutate}:{data:State;busy:boolean;mutate:(p:unknown,m:string,inside?:boolean,endpoint?:string)=>Promise<boolean>}){
 const [start,setStart]=useState(weekStart(data.today)),[dirty,setDirty]=useState(false),[edited,setDraft]=useState<WeeklyReview>(()=>data.weeklyReviews.find(r=>r.weekStart===weekStart(data.today))||empty(weekStart(data.today)));
 const operation=useRef<string|null>(null),saved=data.weeklyReviews.find(r=>r.weekStart===start),draft=dirty?edited:saved||empty(start),summary=weeklySummary(data,start),pending=pendingTasks(data);
 const guard=useUnsavedChanges();
 function update(next:WeeklyReview){guard.edited();setDraft(next);setDirty(true);operation.current=null;}
 async function save(){operation.current??=crypto.randomUUID();const ok=await mutate({action:'review',weekStart:start,version:draft.version,operationId:operation.current,fields:{wentWell:draft.wentWell,obstacles:draft.obstacles,change:draft.change,priorityIds:draft.priorityIds}},'Weekly reflection and priorities saved.',false,'/api/planning');if(ok){setDirty(false);operation.current=null;}return ok;}
 useDraftProtection(dirty,'Weekly reflection',save,()=>{setDirty(false);setDraft(saved||empty(start));operation.current=null;});
 const countLabel=(n:number)=>n===0?'No completions recorded':`${n} completed`,actualLabel=(x:{minutes:number;recorded:number;missing:number})=>x.recorded?duration(x.minutes)+' actual time recorded'+(x.missing?' · '+x.missing+' missing time entries':''):x.missing?'Actual duration not recorded':'No duration entries';
 return <section className="review-page" aria-label="Weekly review"><div className="section-heading review-range"><div><h2>{prettyDate(summary.start)} {summary.start.slice(0,4)} – {prettyDate(summary.end)} {summary.end.slice(0,4)}</h2><span>Monday to Sunday · Asia/Kolkata{summary.partial?' · '+(summary.future?'Future week':`Partial week: ${summary.elapsedDays} of 7 days including today; today is still in progress`):''}</span></div><div className="review-navigation"><button className="secondary-button" disabled={busy||dirty} onClick={()=>setStart(addDays(start,-7))}>Previous week</button><label>Choose any day in the week<input type="date" min="2000-01-01" max="2100-12-31" value={start} disabled={busy||dirty} onChange={e=>{if(e.target.value)setStart(weekStart(e.target.value));}}/></label><button className="secondary-button" disabled={busy||dirty} onClick={()=>setStart(addDays(start,7))}>Next week</button></div></div><p className="field-help">Totals reflect recorded completion dates and corrections. “No entries” means nothing was logged, not that you did no work.</p>
 <div className="review-grid"><article><h3>PhD applications</h3><strong className="review-number">{summary.applications.count}</strong><p>Submissions recorded</p>{summary.applications.records.map(a=><p key={a.id}>{a.institution} · {prettyDate(a.submissionDate!)}</p>)}{!!summary.applications.legacy.length&&<small>Includes {summary.applications.legacy.length} earlier unlinked submission tasks.</small>}</article>
 <article><h3>CSIR lectures</h3><strong className="review-number">{summary.lectures.count}</strong><p>Completions recorded · daily target reached on {summary.lectures.metDays} of {summary.elapsedDays} elapsed days</p>{summary.lectures.unknownTargets>0&&<p className="review-caveat">Historical target settings are unavailable for {summary.lectures.unknownTargets} day(s); comparisons use your current targets.</p>}</article>
 <article><h3>Practice</h3><strong className="review-number">{summary.practice.count}</strong><p>{countLabel(summary.practice.count)}</p><small>{actualLabel(summary.practice)}</small></article><article><h3>Revision</h3><strong className="review-number">{summary.revision.count}</strong><p>{countLabel(summary.revision.count)}</p><small>{actualLabel(summary.revision)}</small></article>
 <article><h3>Research</h3><strong className="review-number">{summary.research.count}</strong><p>{summary.research.hasEntries?countLabel(summary.research.count):'No research entries for this week'}</p><small>{actualLabel(summary.research)}</small></article>
 <article><h3>Workouts & rest</h3><strong className="review-number">{summary.workouts.days} <span>workout days</span></strong><p>{summary.workouts.count} completed workouts · {duration(summary.workouts.minutes)} recorded</p><small>{summary.workouts.restDays} planned rest days{summary.workouts.missingDuration?' · '+summary.workouts.missingDuration+' workout durations not recorded':''}{!summary.workouts.hasEntries?' · No workout or rest entries':''}</small></article>
 <article><h3>Focus sessions</h3><strong className="review-number">{summary.focus.count}</strong><p>{summary.focus.count?'Completed sessions · '+duration(Math.round(summary.focus.minutes))+' focus time':'No completed focus sessions recorded'}</p><small>Focus time can overlap study or research; these durations are not added together.</small></article>
 <article><h3>Distracting phone use</h3><strong className="review-number">{summary.phone.average===null?'—':Math.round(summary.phone.average)+' min'}</strong><p>{summary.phone.average===null?'No manually logged phone-use days':'Daily average across '+summary.phone.days+' logged days'}</p><small>{summary.phone.days} days logged · {summary.phone.missingDays} elapsed days without entries{summary.phone.days?' · '+duration(summary.phone.minutes)+' total':''}</small></article>
 <article><h3>Points & rewards</h3><strong className="review-number">{summary.points.earned} <span>earned</span></strong><p>{summary.points.spent} spent · {summary.points.refunds} refunded · {summary.rewards.count} rewards redeemed (excluding undone entries)</p><small>Earned points follow activity dates and corrections. Spending and refunds follow transaction dates.{!summary.points.ledgerEntries&&!summary.points.earned?' No points entries for this week.':''}</small>{summary.rewards.records.map(r=><p key={r.id}>{r.name} · {r.cost} points{r.refunded?' · refunded':''}</p>)}</article></div>
 <details className="review-daily" open><summary>Daily lecture progress</summary><div className="review-table-scroll"><table><thead><tr><th>Day</th><th>Recorded lectures</th><th>Target / stretch</th><th>Progress</th></tr></thead><tbody>{summary.lectures.daily.map(d=><tr key={d.date}><th>{prettyDate(d.date)}</th><td>{d.future?'Not elapsed':d.count===0&&!d.hasEntries?'No entries':d.count}</td><td>{d.target} / {d.stretch}{!d.future&&!d.historicalKnown?' *':''}</td><td>{d.future?'Upcoming':d.count>=d.stretch?'Stretch reached':d.met?'Target reached':d.count?'In progress':d.hasEntries?'0 completions recorded':'Not logged'}</td></tr>)}</tbody></table></div>{summary.lectures.unknownTargets>0&&<p className="field-help">* Current settings used; the historical target for that day is unavailable.</p>}</details>
 {(summary.research.records.length>0||summary.records.length>0)&&<details className="review-record-notes"><summary>Recorded study and research notes</summary>{[...summary.records,...summary.research.records].map(r=><article key={r.id}><strong>{r.title}</strong><small>{prettyDate(r.completionDate!)} · {r.kind==='research'?'Research':r.sessionType}</small>{r.notes&&<p className="application-notes">{r.notes}</p>}{r.outcome&&<p>Outcome: {r.outcome}</p>}{r.nextStep&&<p>Next step: {r.nextStep}</p>}</article>)}</details>}
 <section className="weekly-reflection"><h2>Reflection & next week</h2><p className="field-help">A few words are enough. Every question is optional.</p><fieldset disabled={busy}><label>What went well?<textarea rows={2} maxLength={3000} value={draft.wentWell} onChange={e=>update({...draft,wentWell:e.target.value})}/></label><label>What got in the way?<textarea rows={2} maxLength={3000} value={draft.obstacles} onChange={e=>update({...draft,obstacles:e.target.value})}/></label><label>What one change will I make next week?<textarea rows={2} maxLength={3000} value={draft.change} onChange={e=>update({...draft,change:e.target.value})}/></label><h3>Priorities for {prettyDate(summary.nextStart)} {summary.nextStart.slice(0,4)} – {prettyDate(addDays(summary.nextStart,6))} {addDays(summary.nextStart,6).slice(0,4)}</h3><p className="field-help">Choose existing pending tasks for next week. This does not automatically schedule or complete them.</p><div className="review-priorities">{pending.map(t=><label key={t.id}><input type="checkbox" checked={draft.priorityIds.includes(t.id)} onChange={e=>update({...draft,priorityIds:e.target.checked?[...draft.priorityIds,t.id]:draft.priorityIds.filter(id=>id!==t.id)})}/><span>{t.title}<small>{goalNames[t.goal]}</small></span></label>)}{!pending.length&&<p className="empty-detail">No pending tasks to select yet.</p>}{draft.priorityIds.filter(id=>!pending.some(t=>t.id===id)).map(id=><p key={id}>{data.tasks.find(t=>t.id===id)?.title||'Earlier selected task'} · completed or archived <button className="text-button" onClick={()=>update({...draft,priorityIds:draft.priorityIds.filter(x=>x!==id)})}>Remove priority</button></p>)}</div></fieldset><div className="planner-actions"><span className="field-help">{dirty?'Unsaved changes.':saved?'Saved to your private account.':'Not saved yet.'}</span><div><button className="text-button" disabled={busy||!dirty} onClick={()=>{setDirty(false);setDraft(saved||empty(start));}}>Discard edits</button><button className="primary-button" disabled={busy||!dirty} onClick={()=>void save()}>{busy?'Saving…':'Save review'}</button></div></div></section></section>;
}
