'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Gift,Plus,Pencil,RotateCcw,Archive,Settings2,Coins} from 'lucide-react';
import {prettyDate} from '@/lib/tasks';
import {exampleRewards,type Reward} from '@/lib/motivation';
import {Modal,FormActions,MotivationSettingsForm,type MotivationProps} from './motivation-ui';
type Draft={id:string;operationId:string;name:string;description:string;cost:number;archived:boolean;original?:Reward};
export default function RewardsView({data,busy,mutate,formError,clearFormError,createRequested}:MotivationProps){
 const [draft,setDraft]=useState<Draft|null>(null),[settings,setSettings]=useState(false),[showArchived,setShowArchived]=useState(false),[redeem,setRedeem]=useState<{reward:Reward;id:string;operationId:string}|null>(null),retry=useRef<{key:string;operationId:string}|null>(null),seen=useRef(createRequested);
 const open=useCallback((original?:Reward,example?:typeof exampleRewards[number])=>{clearFormError();setDraft({id:original?.id||crypto.randomUUID(),operationId:crypto.randomUUID(),name:original?.name||example?.name||'',description:original?.description||example?.description||'',cost:original?.cost||example?.cost||100,archived:original?.archived||false,original});},[clearFormError]);
 useEffect(()=>{if(seen.current!==createRequested){seen.current=createRequested;open();}},[createRequested,open]);
 async function save(e:FormEvent){e.preventDefault();if(draft&&await mutate({action:'reward',id:draft.id,operationId:draft.operationId,...(draft.original?{version:draft.original.version}:{}),fields:draft},'Your reward is saved.',true,'/api/motivation'))setDraft(null);}
 async function quick(payload:Record<string,unknown>,message:string){const key=JSON.stringify(payload);if(retry.current?.key!==key)retry.current={key,operationId:crypto.randomUUID()};if(await mutate({...payload,operationId:retry.current.operationId},message,false,'/api/motivation'))retry.current=null;}
 const rewards=data.rewards.filter(r=>showArchived||!r.archived);
 return <section className="motivation-page" aria-label="Personal rewards"><div className="points-summary"><div><Coins size={22}/><span>Available to spend<strong>{data.availablePoints} <small>points</small></strong></span></div><div><span>Total earned<strong>{data.earnedPoints} <small>points</small></strong></span></div><button className="secondary-button" disabled={busy} onClick={()=>{clearFormError();setSettings(true);}}><Settings2 size={16}/>Point values</button></div>
 {data.availablePoints<0&&<div className="balance-shortfall" role="status">You are {Math.abs(data.availablePoints)} points short after a correction. Your records are correct; redemptions will resume when your balance recovers.</div>}
 <p className="gentle-note">Rewards are a little extra encouragement. Rest, meals and sleep are always yours, independent of points. Missed days never deduct points.</p>
 <div className="motivation-toolbar"><h2>Your personal rewards</h2><label className="inline-check"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Show archived</label></div>
 <div className="reward-grid">{rewards.map(r=><article className={'reward-card '+(r.archived?'archived':'')} key={r.id}><Gift size={23}/><h3>{r.name}</h3>{r.description&&<p>{r.description}</p>}<strong className="reward-cost">{r.cost} <span>points</span></strong><div className="reward-actions"><button className="primary-button" disabled={busy||r.archived||data.availablePoints<r.cost} onClick={()=>{clearFormError();setRedeem({reward:r,id:crypto.randomUUID(),operationId:crypto.randomUUID()});}}>Redeem</button><button className="icon-button" aria-label={'Edit '+r.name} disabled={busy} onClick={()=>open(r)}><Pencil size={17}/></button><button className="icon-button" aria-label={(r.archived?'Restore ':'Archive ')+r.name} disabled={busy} onClick={()=>void quick({action:'reward',id:r.id,version:r.version,fields:{...r,archived:!r.archived}},r.archived?'Reward restored.':'Reward archived.')} >{r.archived?<RotateCcw size={17}/>:<Archive size={17}/>}</button></div>{!r.archived&&data.availablePoints<r.cost&&<small>{r.cost-Math.max(data.availablePoints,0)} more points to go.</small>}{r.archived&&<small>Archived · redemption history stays saved.</small>}</article>)}</div>
 {!rewards.length&&<p className="motivation-empty">Add something you would enjoy, at a cost that feels right for you.</p>}
 <div className="reward-examples"><h3>Start with an example</h3><p>Each example opens an editable form.</p>{exampleRewards.map(r=><button key={r.name} className="secondary-button" disabled={busy} onClick={()=>open(undefined,r)}><Plus size={15}/>{r.name} · {r.cost} pts</button>)}</div>
 <div className="ledger-columns"><section className="ledger-panel"><h2>Redemptions</h2>{!data.redemptions.length&&<p className="field-help">Your redeemed rewards will be saved here.</p>}{data.redemptions.map(r=><article className="ledger-row" key={r.id}><div><strong>{r.name}</strong><span>{prettyDate(r.localDate)} · {r.cost} points{r.refunded?' · Refunded':''}</span></div>{!r.refunded&&<button className="text-button" disabled={busy} onClick={()=>void quick({action:'refund',id:r.id,version:r.version},'Redemption undone. Your points have been refunded.')}><RotateCcw size={15}/>Undo</button>}</article>)}</section><section className="ledger-panel"><h2>Points history</h2>{!data.pointsHistory.length&&<p className="field-help">New completions start earning points now. Your earlier history stays saved.</p>}{data.pointsHistory.map(e=><article className="ledger-row" key={e.sequence}><div><strong>{e.label}</strong><span>{prettyDate(e.localDate)} · {e.action}{e.activityDate?' · work: '+prettyDate(e.activityDate):''}{e.previousDate&&e.previousDate!==e.activityDate?' · previously '+prettyDate(e.previousDate):''}</span></div><b className={e.delta<0?'points-minus':'points-plus'}>{e.delta>0?'+':''}{e.delta}</b></article>)}</section></div>
 <Modal open={!!draft} busy={busy} onClose={()=>setDraft(null)} title={draft?.original?'Edit reward':'Add a personal reward'} description="Choose something enjoyable. Only the name and point cost are required.">{draft&&<form onSubmit={save}><fieldset disabled={busy}><label htmlFor="reward-name">Name</label><input id="reward-name" autoFocus required maxLength={180} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><label htmlFor="reward-description">Description (optional)</label><textarea id="reward-description" rows={3} maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><label htmlFor="reward-cost">Points cost</label><input id="reward-cost" type="number" inputMode="numeric" required min={1} max={100000} value={draft.cost||''} onChange={e=>setDraft({...draft,cost:Number(e.target.value)})}/></fieldset>{formError&&<div className="form-error" role="alert">{formError}</div>}<FormActions busy={busy} onClose={()=>setDraft(null)}/></form>}</Modal>
 <Modal open={!!redeem} busy={busy} onClose={()=>setRedeem(null)} title="Enjoy your reward" description="Review the cost, then redeem once.">{redeem&&<form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'redeem',id:redeem.id,operationId:redeem.operationId,rewardId:redeem.reward.id,rewardVersion:redeem.reward.version},'Reward redeemed. Enjoy it.',true,'/api/motivation'))setRedeem(null);}}><p className="redemption-review"><strong>{redeem.reward.name}</strong><span>{redeem.reward.cost} points · Available: {data.availablePoints}</span></p><p className="field-help">You can undo an accidental redemption here for a full point refund.</p>{formError&&<div className="form-error" role="alert">{formError}</div>}<FormActions busy={busy} disabledSubmit={data.availablePoints<redeem.reward.cost} onClose={()=>setRedeem(null)} label="Redeem reward"/></form>}</Modal>
 <Modal open={settings} busy={busy} onClose={()=>setSettings(false)} title="Points for completed work" description="Set amounts that encourage you.">{settings&&<MotivationSettingsForm section="points" data={data} busy={busy} mutate={mutate} formError={formError} onClose={()=>setSettings(false)}/>}</Modal>
 </section>;
}
