import {historyStatement} from './history-storage';
import {getDb} from '@/db';
import {indiaDate,type Task} from './tasks';
import {defaultMotivation,type MotivationState,type MotivationSettings,type Reward,type Redemption,type HabitRecord,type FocusSession,type PointsEntry,type Award,type HabitEvent} from './motivation';
export const habitColumns='id,kind,data,created_at AS createdAt,updated_at AS updatedAt,version';
export const rewardColumns='id,name,description,cost,archived,created_at AS createdAt,updated_at AS updatedAt,version';
export const focusColumns='id,duration_ms AS durationMs,remaining_ms AS remainingMs,end_at AS endAt,status,phone_free AS phoneFree,completion_date AS completionDate,created_at AS createdAt,updated_at AS updatedAt,version';
export function decodeHabit(r:{id:string;kind:HabitRecord['kind'];data:string;createdAt:string;updatedAt:string;version:number}):HabitRecord{return {...JSON.parse(r.data),id:r.id,kind:r.kind,createdAt:r.createdAt,updatedAt:r.updatedAt,version:r.version};}
export async function readHabit(owner:string,id:string){const r=await getDb().prepare(`SELECT ${habitColumns} FROM habit_records WHERE owner_id=? AND id=?`).bind(owner,id).first<Parameters<typeof decodeHabit>[0]>();return r?decodeHabit(r):null;}
export function decodeFocus(r:FocusSession):FocusSession{return {...r,phoneFree:r.phoneFree===null?null:Boolean(r.phoneFree)};}
export async function readFocus(owner:string,id:string){const r=await getDb().prepare(`SELECT ${focusColumns} FROM focus_sessions WHERE owner_id=? AND id=?`).bind(owner,id).first<FocusSession>();return r?decodeFocus(r):null;}
export async function readReward(owner:string,id:string){const r=await getDb().prepare(`SELECT ${rewardColumns} FROM rewards WHERE owner_id=? AND id=?`).bind(owner,id).first<Reward>();return r?{...r,archived:Boolean(r.archived)}:null;}
export function motivationReadStatements(db:D1Database,owner:string){return [
 db.prepare('SELECT data,version FROM motivation_settings WHERE owner_id=?').bind(owner),
 db.prepare(`SELECT ${rewardColumns} FROM rewards WHERE owner_id=? ORDER BY archived,name,id`).bind(owner),
 db.prepare('SELECT id,reward_id AS rewardId,name,cost,refunded,created_at AS createdAt,local_date AS localDate,version FROM redemptions WHERE owner_id=? ORDER BY created_at DESC,id').bind(owner),
 db.prepare(`SELECT ${habitColumns} FROM habit_records WHERE owner_id=? ORDER BY activity_date DESC,created_at DESC,id`).bind(owner),
 db.prepare(`SELECT ${focusColumns} FROM focus_sessions WHERE owner_id=? ORDER BY created_at DESC,id`).bind(owner),
 db.prepare('SELECT activity_key AS activityKey,kind,amount,active,activity_date AS activityDate,label,first_awarded_at AS firstAwardedAt FROM points_awards WHERE owner_id=? ORDER BY first_awarded_at,activity_key').bind(owner),
 historyStatement(db,owner,'points'),
 historyStatement(db,owner,'habits')
];}
export function decodeMotivation(r:D1Result[],totals:{available:number;earned:number}):MotivationState{const settings=r[0].results[0] as {data:string;version:number}|undefined,history=r[6].results as PointsEntry[];return {motivation:settings?{...defaultMotivation,...JSON.parse(settings.data),version:settings.version}:defaultMotivation,rewards:(r[1].results as Reward[]).map(x=>({...x,archived:Boolean(x.archived)})),redemptions:(r[2].results as Redemption[]).map(x=>({...x,refunded:Boolean(x.refunded)})),habits:(r[3].results as Parameters<typeof decodeHabit>[0][]).map(decodeHabit),focusSessions:(r[4].results as FocusSession[]).map(decodeFocus),awards:(r[5].results as Award[]).map(x=>({...x,active:Boolean(x.active)})),pointsHistory:history,availablePoints:totals.available,earnedPoints:totals.earned,habitEvents:r[7].results as HabitEvent[],serverNow:new Date().toISOString()};}
export async function readMotivationSettings(owner:string):Promise<MotivationSettings>{const r=await getDb().prepare('SELECT data,version FROM motivation_settings WHERE owner_id=?').bind(owner).first<{data:string;version:number}>();return r?{...defaultMotivation,...JSON.parse(r.data),version:r.version}:defaultMotivation;}
export type Proof={table:'events'|'application_events'|'workspace_events'|'habit_events';operationId:string};
export function proofSQL(owner:string,proof:Proof){return {sql:`EXISTS(SELECT 1 FROM ${proof.table} WHERE owner_id=? AND operation_id=?)`,args:[owner,proof.operationId]};}
export function habitEvent(db:D1Database,owner:string,id:string,type:string,next:unknown,previous:unknown,action:string,operationId:string,request:string,now:string,guard='TRUE',args:(string|number|null)[]=[]){return db.prepare(`INSERT INTO habit_events(operation_id,owner_id,entity_id,entity_type,action,snapshot,previous,happened_at,local_date,request) SELECT ?,?,?,?,?,?,?,?,?,? WHERE ${guard}`).bind(operationId,owner,id,type,action,JSON.stringify(next),previous?JSON.stringify(previous):null,now,indiaDate(),request,...args);}
export function habitTask(r:HabitRecord,id:string,now:string,previous?:Task|null):Task{return {...(previous||{}),id,title:r.status==='Rest'?'Planned rest day':r.activityName,goal:'habits',kind:'workout',dueDate:r.date,minutes:Math.max(r.minutes,1),completedAt:r.status==='Completed'||r.status==='Rest'?previous?.completedAt||now:null,completedDate:r.status==='Completed'?r.completionDate:r.status==='Rest'?r.date:null,createdAt:previous?.createdAt||now,updatedAt:now,version:previous?previous.version+1:1,applicationId:null,applicationActionKey:null,workspaceRecordId:null,habitRecordId:r.id,customPoints:0};}
export function habitUpdate(db:D1Database,owner:string,r:HabitRecord,proof:Proof){const p=proofSQL(owner,proof);return db.prepare(`UPDATE habit_records SET data=?,activity_date=?,completion_date=?,status=?,updated_at=?,version=? WHERE owner_id=? AND id=? AND version=? AND ${p.sql}`).bind(JSON.stringify(r),r.date,r.completionDate,r.status,r.updatedAt,r.version,owner,r.id,r.version-1,...p.args);}
