import type {Opportunity} from './applications';
export type ShortlistEntry={checklist?:string[];key:string;institution:string;country:string;projectTitle:string;supervisor:string;link:string;deadline:string;nextAction:string;opportunity:Opportunity};
const verifiedOn='2026-10-02';
export const shortlist:ShortlistEntry[]=[
 {key:'aalto-topic-2-2026',institution:'Aalto University',country:'Finland',projectTitle:'Hybrid Magnonics–Photonics — Topic 2: Magnetic Quantum Materials and Spin-Ion–Magnon Coupling',supervisor:'Sebastiaan van Dijken / Lukáš Flajšman',link:'https://www.aalto.fi/en/open-positions/doctoral-and-postdoctoral-positions-in-hybrid-magnonics-photonics',deadline:'2026-10-23',nextAction:'Tailor my motivation letter for Aalto Topic 2',opportunity:{fitPriority:1,fitNotes:'Strongest direct overlap through rare-earth garnets, magnetic characterization, spin-ion physics and ADR/millikelvin experience.',verifiedOn,recruitment:'Open · rolling review',rolling:true,verificationNote:'Official advert confirms 23 October 2026. Interviews may happen before the deadline. No closing time is specified.'}},
 {key:'hzb-ps-2026-5',institution:'Helmholtz-Zentrum Berlin',country:'Germany',projectTitle:'Magnetic Excitations in Functional Oxides — PS 2026/5',supervisor:'Hebatalla Elnaggar',link:'https://recruitingapp-5181.de.umantis.com/Vacancies/2866/Description/2',deadline:'2026-10-11',nextAction:'Finish my HZB motivation statement and check required documents',opportunity:{fitPriority:2,fitNotes:'Strong overlap through magnetism, magnetic-excitation/CEF analysis, synthesis, characterization and computational analysis.',verifiedOn,recruitment:'Open',verificationNote:'Official advert confirms 11 October 2026. No closing time is specified.'}},
 {key:'mpgc-qm-2027',institution:'Max Planck Graduate Center for Quantum Materials (MPGC-QM)',country:'Germany',projectTitle:'Experimental quantum-materials groups — autumn 2027 intake',supervisor:'Group preferences to be selected',link:'https://www.quantummaterials.mpg.de/application',deadline:'2026-12-08',nextAction:'Select experimental groups in quantum magnetism and low-temperature materials',opportunity:{fitPriority:3,fitNotes:'High programme priority; precise fit depends on selecting experimental groups in quantum magnetism and low-temperature materials research.',aliases:['IMPRS Quantum Materials'],verifiedOn,recruitment:'Open · conflicting older text',verificationNote:'The current heading and recruitment-window notice say OPEN and confirm 8 December 2026 for autumn 2027. The same page retains an older paragraph saying applications cannot be accepted. Discrepancy: check the online form before preparing submission. No closing time is specified.'}},
 {key:'halle-stns-spin-2026',institution:'IMPRS-STNS / MPI of Microstructure Physics, Halle',country:'Germany',projectTitle:'Emerging Spin Dynamics towards Next-Generation Spintronic Devices',supervisor:'Stuart Parkin',link:'https://www.imprs-stns.mpg.de/66944/spintronic-devices',deadline:'2026-11-15',nextAction:'Review the spin-dynamics topic and outline my motivation',opportunity:{fitPriority:4,fitNotes:'Magnetism, materials characterization, cryogenic measurements and automation; spintronics and nanofabrication are development areas.',verifiedOn,recruitment:'Open',closingAt:'2026-11-15T22:59:00.000Z',closingLabel:'15 November 2026, 23:59 CET',closingTimezone:'Europe/Berlin',verificationNote:'Official topic advert specifies 15 November at 23:59 CET; the 2026 call confirms the year. This is 16 November 2026 at 04:29 in Asia/Kolkata.'}},
 {key:'imprs-ufast-2027',institution:'IMPRS UFAST / Max Planck Institute for the Structure and Dynamics of Matter',country:'Germany',projectTitle:'IMPRS UFAST — shared application for PM4 and PM5',supervisor:'Philip Moll / Chunyu Guo',link:'https://www.mpsd.mpg.de/imprs-ufast/apply',deadline:'2026-11-06',nextAction:'Prepare one UFAST motivation letter covering my PM4 and PM5 preferences',opportunity:{fitPriority:5,verifiedOn,recruitment:'Open',workflowLink:'https://www.mpsd.mpg.de/imprs-ufast/apply',verificationNote:'The 2026/2027 call confirms 6 November 2026 and allows up to two project preferences in one application. Reference letters are due 12 November. No closing time is specified.',preferences:[
 {code:'PM4',title:'Dynamic Heat Transport Measurements in Novel Quantum Conditions',fitPriority:5,fitNotes:'Thermodynamic measurements, thermal management, cryogenic instrumentation and automation.',link:'https://www.mpsd.mpg.de/1223954.pdf'},
 {code:'PM5',title:'Exploring Intrinsic Orbital Dynamics in Kagome Metals',fitPriority:6,fitNotes:'Correlated materials and phase transitions; orbital dynamics and microfabrication are development areas.',link:'https://www.mpsd.mpg.de/1223966.pdf'}]}},
 {key:'basel-p2601',institution:'University of Basel / Swiss Nanoscience Institute',country:'Switzerland',projectTitle:'P2601 — Circuit Quantum Electrodynamics to Probe Strongly Interacting Electronic Phases in Atomically Thin Nanoelectronic Devices',supervisor:'Andreas Baumgartner; co-PIs Alexander Grimm / Dominik Zumbühl',link:'https://jobs.unibas.ch/offene-stellen/phd-position-circuit-quantum-electrodynamics-to-probe-strongly-interacting-electronic-phases-in-atomically-thin-nanoelectronic-devices-p2601/59f53cd6-7a82-4d3d-963d-dd11f2913e29',deadline:'2026-12-31',nextAction:'Review P2601 and draft my research-fit statement',opportunity:{fitPriority:7,fitNotes:'Cryogenics, condensed-matter physics and automation; microwave resonators and nanoelectronics are development areas.',verifiedOn,recruitment:'Advertised · may be filled early',rolling:true,verificationNote:'The advert says the application must be completed before 31 December 2026 and the vacancy may be filled at any time. Treat the date as a stated date-only boundary, not a guaranteed full final day. Project leaders verified from the official SNI programme list. No closing time is specified.'}}
];
