-- Steady backend foundation. No live data, sign-in changes or production cutover.
-- Text JSON/date fields intentionally retain the existing serialization contract.
-- All browser roles are read-only until transaction-safe write APIs are ported.

CREATE TABLE public."application_events" (
  "sequence" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "operation_id" text NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "application_id" text NOT NULL,
  "action" text NOT NULL,
  "snapshot" text NOT NULL,
  "previous" text,
  "happened_at" text NOT NULL,
  "local_date" text NOT NULL,
  "request" text NOT NULL
);
CREATE INDEX "idx_application_events_owner_sequence" ON public."application_events" ("owner_id", "sequence");
CREATE UNIQUE INDEX "idx_application_events_operation" ON public."application_events" ("operation_id");
ALTER TABLE public."application_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."application_events" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."application_events" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."application_events" TO authenticated;
GRANT ALL ON TABLE public."application_events" TO service_role;
CREATE POLICY owner_read ON public."application_events" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."applications" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "institution" text NOT NULL,
  "country" text NOT NULL DEFAULT '',
  "project_title" text NOT NULL DEFAULT '',
  "supervisor" text NOT NULL DEFAULT '',
  "link" text NOT NULL DEFAULT '',
  "deadline" text,
  "notes" text NOT NULL DEFAULT '',
  "next_action" text NOT NULL DEFAULT '',
  "stage" text NOT NULL DEFAULT 'Shortlisted',
  "checklist" text NOT NULL DEFAULT '[]',
  "submission_date" text,
  "submission_task_id" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  "opportunity" text NOT NULL DEFAULT '{}'
);
CREATE INDEX "idx_applications_owner" ON public."applications" ("owner_id");
ALTER TABLE public."applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."applications" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."applications" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."applications" TO authenticated;
GRANT ALL ON TABLE public."applications" TO service_role;
CREATE POLICY owner_read ON public."applications" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."day_plans" (
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "date" text NOT NULL,
  "data" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY (owner_id, date)
);
CREATE UNIQUE INDEX "idx_day_plans_owner_date" ON public."day_plans" ("owner_id", "date");
ALTER TABLE public."day_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."day_plans" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."day_plans" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."day_plans" TO authenticated;
GRANT ALL ON TABLE public."day_plans" TO service_role;
CREATE POLICY owner_read ON public."day_plans" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."day_templates" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "data" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE INDEX "idx_day_templates_owner" ON public."day_templates" ("owner_id");
ALTER TABLE public."day_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."day_templates" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."day_templates" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."day_templates" TO authenticated;
GRANT ALL ON TABLE public."day_templates" TO service_role;
CREATE POLICY owner_read ON public."day_templates" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."events" (
  "sequence" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "operation_id" text NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "task_id" text NOT NULL,
  "action" text NOT NULL,
  "snapshot" text NOT NULL,
  "previous" text,
  "happened_at" text NOT NULL,
  "local_date" text NOT NULL,
  "request" text NOT NULL
);
CREATE INDEX "idx_events_owner_sequence" ON public."events" ("owner_id", "sequence");
CREATE UNIQUE INDEX "idx_events_operation" ON public."events" ("operation_id");
ALTER TABLE public."events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."events" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."events" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."events" TO authenticated;
GRANT ALL ON TABLE public."events" TO service_role;
CREATE POLICY owner_read ON public."events" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."focus_sessions" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "duration_ms" bigint NOT NULL,
  "remaining_ms" bigint NOT NULL,
  "end_at" text,
  "status" text NOT NULL,
  "phone_free" integer,
  "completion_date" text,
  "active_key" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX "idx_focus_sessions_active" ON public."focus_sessions" ("owner_id", "active_key");
ALTER TABLE public."focus_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."focus_sessions" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."focus_sessions" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."focus_sessions" TO authenticated;
GRANT ALL ON TABLE public."focus_sessions" TO service_role;
CREATE POLICY owner_read ON public."focus_sessions" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."habit_events" (
  "sequence" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "operation_id" text NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "entity_id" text NOT NULL,
  "entity_type" text NOT NULL,
  "action" text NOT NULL,
  "snapshot" text NOT NULL,
  "previous" text,
  "happened_at" text NOT NULL,
  "local_date" text NOT NULL,
  "request" text NOT NULL
);
CREATE INDEX "idx_habit_events_owner" ON public."habit_events" ("owner_id", "sequence");
CREATE UNIQUE INDEX "idx_habit_events_operation" ON public."habit_events" ("operation_id");
ALTER TABLE public."habit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."habit_events" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."habit_events" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."habit_events" TO authenticated;
GRANT ALL ON TABLE public."habit_events" TO service_role;
CREATE POLICY owner_read ON public."habit_events" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."habit_records" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "kind" text NOT NULL,
  "data" text NOT NULL,
  "activity_date" text NOT NULL,
  "completion_date" text,
  "status" text NOT NULL,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE INDEX "idx_habit_records_day" ON public."habit_records" ("owner_id", "kind", "completion_date", "status");
ALTER TABLE public."habit_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."habit_records" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."habit_records" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."habit_records" TO authenticated;
GRANT ALL ON TABLE public."habit_records" TO service_role;
CREATE POLICY owner_read ON public."habit_records" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."motivation_settings" (
  "owner_id" uuid PRIMARY KEY NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "data" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  "updated_at" text NOT NULL
);
ALTER TABLE public."motivation_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."motivation_settings" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."motivation_settings" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."motivation_settings" TO authenticated;
GRANT ALL ON TABLE public."motivation_settings" TO service_role;
CREATE POLICY owner_read ON public."motivation_settings" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."planning_events" (
  "sequence" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "operation_id" text NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "entity_id" text NOT NULL,
  "entity_type" text NOT NULL,
  "snapshot" text NOT NULL,
  "previous" text,
  "happened_at" text NOT NULL,
  "request" text NOT NULL
);
CREATE INDEX "idx_planning_events_owner" ON public."planning_events" ("owner_id", "sequence");
CREATE UNIQUE INDEX "idx_planning_events_operation" ON public."planning_events" ("operation_id");
ALTER TABLE public."planning_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."planning_events" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."planning_events" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."planning_events" TO authenticated;
GRANT ALL ON TABLE public."planning_events" TO service_role;
CREATE POLICY owner_read ON public."planning_events" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."points_awards" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "activity_key" text NOT NULL,
  "kind" text NOT NULL,
  "amount" integer NOT NULL,
  "active" integer NOT NULL DEFAULT 0,
  "activity_date" text NOT NULL,
  "label" text NOT NULL,
  "first_awarded_at" text NOT NULL
);
CREATE INDEX "idx_points_awards_daily" ON public."points_awards" ("owner_id", "kind", "activity_date", "active");
CREATE UNIQUE INDEX "idx_points_awards_activity" ON public."points_awards" ("owner_id", "activity_key");
ALTER TABLE public."points_awards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."points_awards" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."points_awards" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."points_awards" TO authenticated;
GRANT ALL ON TABLE public."points_awards" TO service_role;
CREATE POLICY owner_read ON public."points_awards" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."points_ledger" (
  "sequence" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "event_key" text NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "activity_key" text NOT NULL,
  "action" text NOT NULL,
  "delta" integer NOT NULL,
  "activity_date" text,
  "previous_date" text,
  "label" text NOT NULL,
  "happened_at" text NOT NULL,
  "local_date" text NOT NULL
);
CREATE INDEX "idx_points_ledger_owner" ON public."points_ledger" ("owner_id", "sequence");
CREATE UNIQUE INDEX "idx_points_ledger_event" ON public."points_ledger" ("owner_id", "event_key");
ALTER TABLE public."points_ledger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."points_ledger" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."points_ledger" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."points_ledger" TO authenticated;
GRANT ALL ON TABLE public."points_ledger" TO service_role;
CREATE POLICY owner_read ON public."points_ledger" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."redemptions" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "reward_id" text NOT NULL,
  "name" text NOT NULL,
  "cost" integer NOT NULL,
  "refunded" integer NOT NULL DEFAULT 0,
  "created_at" text NOT NULL,
  "local_date" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE INDEX "idx_redemptions_owner" ON public."redemptions" ("owner_id");
ALTER TABLE public."redemptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."redemptions" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."redemptions" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."redemptions" TO authenticated;
GRANT ALL ON TABLE public."redemptions" TO service_role;
CREATE POLICY owner_read ON public."redemptions" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."rewards" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "name" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "cost" integer NOT NULL,
  "archived" integer NOT NULL DEFAULT 0,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE INDEX "idx_rewards_owner" ON public."rewards" ("owner_id");
ALTER TABLE public."rewards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."rewards" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."rewards" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."rewards" TO authenticated;
GRANT ALL ON TABLE public."rewards" TO service_role;
CREATE POLICY owner_read ON public."rewards" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."tasks" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "title" text NOT NULL,
  "goal" text NOT NULL,
  "kind" text NOT NULL,
  "due_date" text NOT NULL,
  "minutes" integer NOT NULL,
  "completed_at" text,
  "completed_date" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  "application_id" text,
  "application_action_key" text,
  "workspace_record_id" text,
  "habit_record_id" text,
  "custom_points" integer NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX "idx_tasks_habit_record" ON public."tasks" ("owner_id", "habit_record_id");
CREATE UNIQUE INDEX "idx_tasks_workspace_record" ON public."tasks" ("owner_id", "workspace_record_id");
CREATE UNIQUE INDEX "idx_tasks_application_action" ON public."tasks" ("owner_id", "application_id", "application_action_key");
CREATE INDEX "idx_tasks_owner" ON public."tasks" ("owner_id");
ALTER TABLE public."tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tasks" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."tasks" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."tasks" TO authenticated;
GRANT ALL ON TABLE public."tasks" TO service_role;
CREATE POLICY owner_read ON public."tasks" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."weekly_reviews" (
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "week_start" text NOT NULL,
  "data" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY (owner_id, week_start)
);
CREATE UNIQUE INDEX "idx_weekly_reviews_owner_week" ON public."weekly_reviews" ("owner_id", "week_start");
ALTER TABLE public."weekly_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."weekly_reviews" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."weekly_reviews" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."weekly_reviews" TO authenticated;
GRANT ALL ON TABLE public."weekly_reviews" TO service_role;
CREATE POLICY owner_read ON public."weekly_reviews" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."workspace_catalog" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "kind" text NOT NULL,
  "name" text NOT NULL,
  "parent_id" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE INDEX "idx_workspace_catalog_owner" ON public."workspace_catalog" ("owner_id");
ALTER TABLE public."workspace_catalog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."workspace_catalog" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."workspace_catalog" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."workspace_catalog" TO authenticated;
GRANT ALL ON TABLE public."workspace_catalog" TO service_role;
CREATE POLICY owner_read ON public."workspace_catalog" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."workspace_events" (
  "sequence" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "operation_id" text NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "entity_id" text NOT NULL,
  "entity_type" text NOT NULL,
  "action" text NOT NULL,
  "snapshot" text NOT NULL,
  "previous" text,
  "happened_at" text NOT NULL,
  "local_date" text NOT NULL,
  "request" text NOT NULL
);
CREATE INDEX "idx_workspace_events_owner_sequence" ON public."workspace_events" ("owner_id", "sequence");
CREATE UNIQUE INDEX "idx_workspace_events_operation" ON public."workspace_events" ("operation_id");
ALTER TABLE public."workspace_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."workspace_events" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."workspace_events" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."workspace_events" TO authenticated;
GRANT ALL ON TABLE public."workspace_events" TO service_role;
CREATE POLICY owner_read ON public."workspace_events" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."workspace_records" (
  "id" text PRIMARY KEY NOT NULL,
  "owner_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "kind" text NOT NULL,
  "data" text NOT NULL,
  "source_record_id" text,
  "followup_key" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX "idx_workspace_records_followup" ON public."workspace_records" ("owner_id", "source_record_id", "followup_key");
CREATE INDEX "idx_workspace_records_owner" ON public."workspace_records" ("owner_id");
ALTER TABLE public."workspace_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."workspace_records" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."workspace_records" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."workspace_records" TO authenticated;
GRANT ALL ON TABLE public."workspace_records" TO service_role;
CREATE POLICY owner_read ON public."workspace_records" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

CREATE TABLE public."workspace_settings" (
  "owner_id" uuid PRIMARY KEY NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  "data" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  "updated_at" text NOT NULL
);
ALTER TABLE public."workspace_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."workspace_settings" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."workspace_settings" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."workspace_settings" TO authenticated;
GRANT ALL ON TABLE public."workspace_settings" TO service_role;
CREATE POLICY owner_read ON public."workspace_settings" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);

-- Identity mapping is administrative; an email match must never silently merge accounts.
CREATE SCHEMA steady_private;
REVOKE ALL ON SCHEMA steady_private FROM PUBLIC, anon, authenticated;
CREATE TABLE steady_private.identity_mappings (
  source_site_id text NOT NULL,
  source_owner_id text NOT NULL,
  auth_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  verified_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_site_id, source_owner_id),
  UNIQUE (source_site_id, auth_user_id)
);
ALTER TABLE steady_private.identity_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE steady_private.identity_mappings FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE steady_private.identity_mappings FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
